[package]
name = "http-range-example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
axum-range = "0.5.0"
colored = "2.0"
memory-stats = "1.0"
humansize = "2.1"
